namespace TinyProxy.Protocol;

/// <summary>
/// Handles the statistics page.
/// Aligns with tinyproxy C's stats.c showstats() function.
/// </summary>
public sealed class StatsHandler
{
    private readonly ILogger _logger;
    private readonly Configuration _config;
    private readonly Stats _stats;

    public StatsHandler(ILogger logger, Configuration config, Stats stats)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _config = config ?? throw new ArgumentNullException(nameof(config));
        _stats = stats ?? throw new ArgumentNullException(nameof(stats));
    }

    /// <summary>
    /// Handles the statistics page request.
    /// Sends an HTML page with runtime statistics.
    /// </summary>
    public async ValueTask HandleStatsPageAsync(Socket clientSocket, CancellationToken token)
    {
        var snapshot = _stats.GetSnapshot();

        var html = $@"<?xml version=""1.0"" encoding=""UTF-8"" ?>
<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.1//EN"" ""http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"">
<html>
<head>
    <title>TinyProxy.NET run-time statistics</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
        .container {{ background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; border-bottom: 2px solid #0078d4; padding-bottom: 10px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        td {{ padding: 12px; border-bottom: 1px solid #eee; }}
        td:first-child {{ font-weight: bold; color: #555; width: 50%; }}
        tr:last-child td {{ border-bottom: none; }}
        hr {{ border: none; border-top: 1px solid #ddd; margin: 20px 0; }}
        .footer {{ color: #888; font-size: 0.9em; }}
    </style>
</head>
<body>
    <div class=""container"">
        <h1>TinyProxy.NET run-time statistics</h1>
        <table>
            <tr><td>Number of open connections:</td><td>{snapshot.ActiveConnections}</td></tr>
            <tr><td>Number of requests:</td><td>{snapshot.TotalRequests}</td></tr>
            <tr><td>Number of bad connections:</td><td>{snapshot.FailedRequests}</td></tr>
            <tr><td>Number of denied connections:</td><td>{snapshot.DeniedRequests}</td></tr>
            <tr><td>Number of refused connections:</td><td>{snapshot.RefusedConnections}</td></tr>
            <tr><td>Bytes sent:</td><td>{FormatBytes(snapshot.BytesSent)}</td></tr>
            <tr><td>Bytes received:</td><td>{FormatBytes(snapshot.BytesReceived)}</td></tr>
        </table>
        <hr>
        <p class=""footer"">Generated by <em>TinyProxy.NET</em> - A high-performance .NET proxy server</p>
    </div>
</body>
</html>";

        var response = $"HTTP/1.1 200 OK\r\n" +
                       $"Content-Type: text/html; charset=UTF-8\r\n" +
                       $"Content-Length: {Encoding.UTF8.GetByteCount(html)}\r\n" +
                       $"Cache-Control: no-cache\r\n" +
                       $"Connection: close\r\n" +
                       $"\r\n{html}";

        var buffer = Encoding.UTF8.GetBytes(response);
        await clientSocket.SendAllAsync(buffer, token).ConfigureAwait(false);

        if (_config.Verbose) _logger.LogInfo("Statistics page served");
    }

    private static string FormatBytes(long bytes)
    {
        const long KB = 1024;
        const long MB = KB * 1024;
        const long GB = MB * 1024;

        return bytes switch
        {
            < KB => $"{bytes} B",
            < MB => $"{bytes / KB:F2} KB",
            < GB => $"{bytes / MB:F2} MB",
            _ => $"{bytes / GB:F2} GB"
        };
    }
}
